//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMoveNew.Views.user {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMoveNew.Views.user.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نافل.
        /// </summary>
        public static string Carrier {
            get {
                return ResourceManager.GetString("Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انا .....
        /// </summary>
        public static string IAma {
            get {
                return ResourceManager.GetString("IAma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انضم الينا.
        /// </summary>
        public static string JoinUMove {
            get {
                return ResourceManager.GetString("JoinUMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دعنا ننقل الاشياء الخاصة بك بسرعة وامان.
        /// </summary>
        public static string Let {
            get {
                return ResourceManager.GetString("Let", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عميل شحن.
        /// </summary>
        public static string ShippingCustomer {
            get {
                return ResourceManager.GetString("ShippingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكننا ان نجمع او نخزن الشياء الخاصة بك.
        /// </summary>
        public static string We {
            get {
                return ResourceManager.GetString("We", resourceCulture);
            }
        }
    }
}
