//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMoveNew.Views.Trips {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Categories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMoveNew.Views.Trips.Categories", typeof(Categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيارات، قوارب، دراجات نارية,....
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بناء، مزارع.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شحن.
        /// </summary>
        public static string Freight {
            get {
                return ResourceManager.GetString("Freight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأثاث والأجهزةو.....
        /// </summary>
        public static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدات ثقيلة.
        /// </summary>
        public static string HeavyEquipment {
            get {
                return ResourceManager.GetString("HeavyEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بضائع منزلية.
        /// </summary>
        public static string HouseholdGoods {
            get {
                return ResourceManager.GetString("HouseholdGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون تعب نوفر شحن لأى شئ.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلعة اخرى.
        /// </summary>
        public static string OtherItem {
            get {
                return ResourceManager.GetString("OtherItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر فئة.
        /// </summary>
        public static string SELECTACATEGORY {
            get {
                return ResourceManager.GetString("SELECTACATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شحن  شيء آخر ؟.
        /// </summary>
        public static string Shippingsomethingelse {
            get {
                return ResourceManager.GetString("Shippingsomethingelse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حمولة شاحنةاو اقل من حمولة.
        /// </summary>
        public static string Truckload {
            get {
                return ResourceManager.GetString("Truckload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركبات.
        /// </summary>
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
    }
}
