//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMoveNew.Views.Trips {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Household {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Household() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMoveNew.Views.Trips.Household", typeof(Household).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحف.
        /// </summary>
        public static string Antiques {
            get {
                return ResourceManager.GetString("Antiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأجهزة.
        /// </summary>
        public static string Appliances {
            get {
                return ResourceManager.GetString("Appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أثاث.
        /// </summary>
        public static string Furniture {
            get {
                return ResourceManager.GetString("Furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجهزة الكترونيه.
        /// </summary>
        public static string HomeElectronics {
            get {
                return ResourceManager.GetString("HomeElectronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدات خارجية.
        /// </summary>
        public static string OutdoorEquipment {
            get {
                return ResourceManager.GetString("OutdoorEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدات رياضية.
        /// </summary>
        public static string SportingEquipment {
            get {
                return ResourceManager.GetString("SportingEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو نوع البضائع المنزلية؟.
        /// </summary>
        public static string WHATTYPEOFHOUSEHOLDGOOD {
            get {
                return ResourceManager.GetString("WHATTYPEOFHOUSEHOLDGOOD", resourceCulture);
            }
        }
    }
}
