//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMoveNew.Views.Trips {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vehicles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vehicles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UMoveNew.Views.Trips.Vehicles", typeof(Vehicles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيارات والشاحنات الخفيفة.
        /// </summary>
        public static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدات مزارع.
        /// </summary>
        public static string FarmEquipment {
            get {
                return ResourceManager.GetString("FarmEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدراجات النارية ودراجات نارية صغيرة.
        /// </summary>
        public static string Motorcycles {
            get {
                return ResourceManager.GetString("Motorcycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوارب آلية.
        /// </summary>
        public static string PowerBoats {
            get {
                return ResourceManager.GetString("PowerBoats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دراجات رياضية.
        /// </summary>
        public static string Powersports {
            get {
                return ResourceManager.GetString("Powersports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركبات للترفية.
        /// </summary>
        public static string RecreationalVehicles {
            get {
                return ResourceManager.GetString("RecreationalVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما نوع المركبات ؟.
        /// </summary>
        public static string WHATTYPEOFVEHICLE {
            get {
                return ResourceManager.GetString("WHATTYPEOFVEHICLE", resourceCulture);
            }
        }
    }
}
